name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *' # todo dia à meia-noite
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update cache buster
        run: |
          sed -i "s/v=[0-9]*/v=$(date +%s)/" README.md

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update stats cache [skip ci]" || echo "No changes"
          git push
